# Who run test, should clone this file to a new file "test_config.yml" at the current directory and fill these config fields according to the running environment
# If "test_config.yml" not exist, this default file will be loaded
host: localhost
port: 5432
user: postgres
password: 123@123a
dbname: test